# 📁 Chrome Extension changes
Chrome Extension:
  - 'chrome-extension/**'

# ⚛️ React App changes
React App:
  - 'react-app/**'

# 🚀 New Features
feature:
  - '**/features/**'
  - '**/new/**'

# 🐛 Bug Fixes
bug:
  - '**/bugfix/**'
  - '**/*.fix.js'

# 💄 UI Changes
ui:
  - '**/components/**'
  - '**/*.css'
  - '**/*.scss'

# 🧹 Refactoring
refactor:
  - '**/refactor/**'
  - '**/*.ref.js'

# 📝 Documentation
docs:
  - '**/*.md'
  - 'docs/**'

# 📦 Dependency Updates
config:
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'
  - 'webpack.*.js'
  - '.github/workflows/**'
