chrome-extension:
  - "chrome-extension/**"

react-app:
  - "react-app/**"

feature:
  - "**/features/**"
  - "**/new/**"

bug:
  - "**/bugfix/**"
  - "**/*.fix.js"

ui:
  - "**/components/**"
  - "**/*.css"
  - "**/*.scss"

refactor:
  - "**/refactor/**"
  - "**/*.ref.js"

docs:
  - "**/*.md"
  - "docs/**"

config:
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"
  - "webpack.*.js"
  - ".github/workflows/**"
