changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - feature
        - enhancement

    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix

    - title: 💄 UI Changes
      labels:
        - ui
        - design

    - title: 🧹 Refactoring
      labels:
        - refactor

    - title: 📦 Dependency Updates
      labels:
        - dependencies

    - title: 📝 Documentation
      labels:
        - docs

    - title: 🛠 Other Changes
      labels:
        - "*"
